### ISSUE TITLE
全局模式无效

### ISSUE THREAD

**Issue by ayykbzq** [dream7180/ClashWarden#1]
仪表盘的【设置】里点击 全局/规则/直连 不会显示高亮，在【连接】里看就确实是切换了。
不过最大的问题是选择全局的时候，【连接】里的节点链显示的是 GLOBAL --> DIRECT，实际效果就是直连

**Comment by dream7180** [comment]
仪表盘我也无能为力，不过1.1新版增加了另一个仪表盘Yacd，你可以切换试试！
